#!/usr/bin/env bun
/**
 * Encrypt a schedule JSON with a password and write the ciphertext blob
 * into the frontend source so sensitive data is not stored in plaintext.
 *
 * Usage:
 *   bun encrypt-defaults.ts                        # encrypts default-schedule.json, prompts for password
 *   bun encrypt-defaults.ts mypassword             # encrypts default-schedule.json with password
 *   bun encrypt-defaults.ts mypassword default    # encrypts default-schedule.json
 *   bun encrypt-defaults.ts mypassword alt        # encrypts alt-schedule.json
 *
 * To clear an encrypted schedule:
 *   bun encrypt-defaults.ts --clear              # clears default
 *   bun encrypt-defaults.ts --clear alt          # clears alt
 */

import { encryptData } from './vite-project/src/crypto.js';

const SCHEDULE_FILES: { [key: string]: { input: string; output: string } } = {
  default: {
    input: './data/default-schedule.json',
    output: './vite-project/src/data/defaults-encrypted.js'
  },
  alt: {
    input: './data/alt-schedule.json',
    output: './vite-project/src/data/alt-encrypted.js'
  }
};

async function promptPassword(): Promise<string> {
  process.stdout.write('Password: ');
  const buf: number[] = [];
  process.stdin.setRawMode(true);
  process.stdin.resume();
  return new Promise((resolve) => {
    process.stdin.on('data', (chunk: Buffer) => {
      for (const byte of chunk) {
        if (byte === 13 || byte === 10) { // Enter
          process.stdin.setRawMode(false);
          process.stdin.pause();
          process.stdout.write('\n');
          resolve(Buffer.from(buf).toString());
          return;
        }
        if (byte === 127 || byte === 8) { // Backspace
          if (buf.length) { buf.pop(); process.stdout.write('\b \b'); }
        } else {
          buf.push(byte);
          process.stdout.write('*');
        }
      }
    });
  });
}

async function main() {
  const arg1 = process.argv[2];
  const arg2 = process.argv[3];

  // Parse arguments: password and optional schedule name
  let password = '';
  let scheduleKey = 'default';

  if (arg1 === '--clear') {
    scheduleKey = arg2 || 'default';
    if (!SCHEDULE_FILES[scheduleKey]) {
      console.error(`Unknown schedule: ${scheduleKey}`);
      process.exit(1);
    }
    const { output } = SCHEDULE_FILES[scheduleKey]!;
    const varName = scheduleKey === 'default' ? 'ENCRYPTED_DEFAULT' : 'ENCRYPTED_ALT';
    await Bun.write(output, `// No encrypted ${scheduleKey} — using plaintext from defaults.js\nexport const ${varName} = null;\n`);
    console.log(`Cleared ${scheduleKey}. ${output} reset to null.`);
    return;
  }

  // Parse password and schedule
  password = arg1 || '';
  if (arg2 && SCHEDULE_FILES[arg2]) {
    scheduleKey = arg2;
  }

  if (!password) {
    password = await promptPassword();
  }
  if (!password) {
    console.error('Password cannot be empty.');
    process.exit(1);
  }

  if (!SCHEDULE_FILES[scheduleKey]) {
    console.error(`Unknown schedule: ${scheduleKey}. Use 'default' or 'alt'.`);
    process.exit(1);
  }
  const { input, output } = SCHEDULE_FILES[scheduleKey]!;
  const scheduleFile = Bun.file(input);
  if (!await scheduleFile.exists()) {
    console.error(`File not found: ${input}`);
    process.exit(1);
  }

  const rawJson = await scheduleFile.json();
  console.log(`Encrypting ${scheduleKey}-schedule...`);
  const payload = await encryptData(password, rawJson);

  const varName = scheduleKey === 'default' ? 'ENCRYPTED_DEFAULT' : 'ENCRYPTED_ALT';
  const outputCode = `// Auto-generated by encrypt-defaults.ts — do not edit manually.
// To regenerate: bun encrypt-defaults.ts <password> ${scheduleKey}
// To clear:      bun encrypt-defaults.ts --clear ${scheduleKey}
export const ${varName} = ${JSON.stringify(payload)};
`;

  await Bun.write(output, outputCode);
  console.log(`Done. Encrypted blob written to ${output}`);
  console.log(`The app will now prompt for a password on first load (when no saved data exists).`);
}

main().catch(e => { console.error(e); process.exit(1); });
